### ISSUE TITLE
没办法注册用户

### ISSUE THREAD

**Issue by NuyOahIII** [wdsjxh/fiddler_tools#2]
有其它容器，所以端口换成了8002
![image](https://user-images.githubusercontent.com/61104521/129867344-ed38baff-b975-4687-aa6c-0c6a8a6ecd5f.png)

**Comment by wdsjxh** [comment]
有其他报错信息没？

**Comment by NuyOahIII** [comment]
![image](https://user-images.githubusercontent.com/61104521/129868263-6ed113d5-bc10-456c-aa3b-d33d7fcb06d1.png)
现在报错是这个样子了

**Comment by NuyOahIII** [comment]
有地方可以看到日志吗？

**Comment by NuyOahIII** [comment]
![image](https://user-images.githubusercontent.com/61104521/129868974-488c1546-1877-4f9b-85d9-842d144d3e85.png)
监听这一步我没有做，我在my.conf文件里面没有找到绑定IP的项目。我用的不是kali搭建

**Comment by wdsjxh** [comment]
> ![image](https://user-images.githubusercontent.com/61104521/129868974-488c1546-1877-4f9b-85d9-842d144d3e85.png)
> 监听这一步我没有做，我在my.conf文件里面没有找到绑定IP的项目。我用的不是kali搭建

docker容器是连接宿主机的MySQL，所以需要设置监听非本机，你进入容器，连接宿主机MySQL试试，连不了的话就是这个原因了。还有就是授权数据库那里，172.17.0.2是容器ip，如果不一样也需要对应改下， _c 授予docker对Mysql数据库操作权限

sudo mysql -uroot -p
进入MySQL后，授权对应docker容器IP（172.17.0.2）访问fiddler_log数据库权限_

**Comment by NuyOahIII** [comment]
![image](https://user-images.githubusercontent.com/61104521/129994499-e40ff1c8-cc4b-4c06-bc9b-b2114b2d5a18.png)
我进容器以后直接没有mysql命令

**Comment by NuyOahIII** [comment]
![image](https://user-images.githubusercontent.com/61104521/129998438-afa196f2-e74b-4122-a521-a6692567a1ab.png)
我的IP是对的
![image](https://user-images.githubusercontent.com/61104521/129998490-9a614e52-bd67-4ed0-8968-9402ca5cba00.png)
数据库也同样设置了访问权限

**Comment by NuyOahIII** [comment]
大佬可以留个QQ（2415174763）吗？加个联系方式，搞半天还是没部署起来。。。

**Comment by wdsjxh** [comment]
1739642302



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月19日(周四) 上午10:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wdsjxh/fiddler_tools] 没办法注册用户 (#2)




 
大佬可以留个QQ吗？加个联系方式，搞半天还是没部署起来。。。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wdsjxh** [comment]
最后是docker镜像一处bug，现已修复并同步更新，还有数据库导入失败，报索引长度超过限制，Index column size too large. The maximum column size is 767 bytes.，解决参考[Index column size too large. The maximum column size is 767 bytes](https://github.com/wdsjxh/fiddler_tools/issues/1)

**Comment by ssunadmin** [comment]
大佬可以留个QQ（807965684）吗？加个联系方式，搞半天还是没部署起来。。。

**Comment by ssunadmin** [comment]
我也是用docker部署，注册提示没法注册
